### ISSUE TITLE
Wrong folder name when installed with Kirby CLI

### ISSUE THREAD

**Issue by wottpal** [TimOetting/kirby-gallery#11]
Hey Tim,
first: thanks for this nice custom field. Just wanted to let you know that I've installed the plugin via Kirby CLI and it created the directory `site/fields/kirby-gallery` for it but if I am right this should be `site/fields/gallery` instead to be recognized by the panel correctly. Don't know if you can do something about this or this is a Kirby CLI flaw :)

Dennis

**Comment by mxub** [comment]
PR #8 should fix it - but it is still not merged :(

**Comment by TimOetting** [comment]
Just merged it. Thanks for the help maxxst!
