### ISSUE TITLE
Video support?

### ISSUE THREAD

**Issue by babyPrince** [TimOetting/kirby-gallery#15]
Hey @TimOetting, is it possible to tweak the plugin to support video as well? Mix image and video files together?

**Comment by luukjanssens** [comment]
+1

**Comment by TimOetting** [comment]
Hey,

you might have heard that Kirby 3 came out some days ago. It comes with an entirely new panel that makes this plugin obsolete. There will therefore not be any further work from my side on this plugin anymore. I hope you understand.
