### ISSUE TITLE
Does not work ?

### ISSUE THREAD

**Issue by H-i-red** [TimOetting/kirby-gallery#2]
Hi I tested it in a fresh install:

```
Toolkit version: 2.3.0
Kirby version: 2.3.0
Panel version: 2.3.0 
```

When I select images it simply does not store any value to the text file, and does not show the selected images.

**Comment by H-i-red** [comment]
Mamp and on a mac.

**Comment by H-i-red** [comment]
Log : (post to undefined)

```
post: http://localhost/new/panel/pages/about/undefined
get: http://localhost/new/panel/pages/about/edit
```

**Comment by H-i-red** [comment]
sir you need to change your mainForm variable to work with different blueprints.. ;)

```
// var mainForm  = $('form.form-blueprint-project');
var mainForm  = element.closest('form');
```

No it works!! Tjoohooo !

**Comment by TimOetting** [comment]
Hey,

Thanks for the help. Didn't think about how this class name was constructed. I fixed it now.
