### ISSUE TITLE
add package.json to allow for Kirby cli installation

### ISSUE THREAD

**Issue by digiltd** [TimOetting/kirby-gallery#3]
Hi

Any chance you can add a package.json file the to the root of the repo?

```
{
    "name": "kirby-gallery",
    "description": "A gallery field for Kirby CMS",
    "author": "Tim Ötting <tim@whateveryouremailaddresis.com>",
    "license": "MIT",
    "version": "1.1",
    "type": "kirby-field"
}
```

Then Kirby cli users can install easily with`kirby plugin:install TimOetting/kirby-gallery`

Thanks

**Comment by jorgemartins** [comment]
`"name": "kirby-gallery",`
CLI creates a folder, and the folder should have the same name as the PHP file inside, that is gallery.php, so it should be:
`"name": "gallery",`
